### ISSUE TITLE
Mandate 2FA for organization and prune membership

### ISSUE THREAD

**Issue by szhorvat** [igraph/.github#3]
For security reasons, and especially for increasing user trust, I suggest the following:

 - Mandate GitHub 2FA for everyone with commit access to important igraph repos. The easy way to do this is to mandate 2FA for all GitHub organization members. There is a setting for this. Enabling it would kick off people without 2FA, but there are no such members at the moment. Thus enabling the setting just provides security.
 - Make all GitHub organization members public to increase transparency. (I don't have a strong opinion on this one.)
 - Remove organization members, added many years ago, with whom we do not have contact. There are several people whom I don't know, who did not contribute in the past few years (or even before), but have write access to core repos. This should be managed.

List of people is here: https://github.com/orgs/igraph/people You need to be a member to see the full list.

This is specifically about managing write access and security. It is not about "core members" as set out in the governance document. Note that people with full write access can add a commit that looks like it came from someone else than them. They can also force-push and make such a commit appear to have been added in the distant past. After what happened to XZ ([1](https://tukaani.org/xz-backdoor/), [2](https://arstechnica.com/security/2024/03/backdoor-found-in-widely-used-linux-utility-breaks-encrypted-ssh-connections/)), this should be taken seriously.

Let me know your thoughts.

**Comment by maelle** [comment]
- I agree on the 2FA mandate, anyway GitHub is slowly making it compulsory for all users.
- You cannot make GitHub organization members public, that's something each member has to do on their side. https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership
- Your last point also makes sense, I think it's called Principle of Least Privilege? https://en.wikipedia.org/wiki/Principle_of_least_privilege

**Comment by ntamas** [comment]
FYI, 2FA is now mandatory.

The base role of the organization is "No permissions" at the moment so we can keep people in the organization to recognize their past contributions while revoking write access to core repositories.

**Comment by szhorvat** [comment]
@ragibson @schochastics This is a heads up that I removed your write access to the core igraph repositories per the above discussion, since you were not contributing in the past few years in a way that requires direct commit access. You are still members of the igraph GitHub organization (and you can control whether to make this membership public or private).
